### ISSUE TITLE
Run with no command line arguments results in crash

### ISSUE THREAD

**Issue by timchurchard** [trashhalo/readcli#4]
Using linux amd64 build from release 0.0.1 on Ubuntu 20.04 
```$ readcli
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.main()
```

**Comment by trashhalo** [comment]
Fixed in [v0.0.2](https://github.com/trashhalo/readcli/releases/tag/v0.0.2)

![](https://media.giphy.com/media/ukJ4Gueb2QgUHcvjro/giphy.gif)
